[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "b7QbsGwOtK"
weight = 9999

[[main]]
name = "Resume"
url = "https://drive.proton.me/urls/8ZS3329FS8#ETJwYLkvHclQ"
identifier = "huh5OUFWR9"
weight = 9999

[[footer]]
none = "none"

[[footer]]
name = "Tags"
pageRef = "tags"
identifier = "Zt2cU0m86d"
weight = 9999
